[package]
name = "mule"
version = "0.0.0"
authors = ["Amr Hassan <amr.hassan@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.4.0", features = ["fs", "io-util", "rt-multi-thread", "macros"] }
thiserror = "1"
derive_more = "0"
itertools = "0.10"
maplit = "1.0.2"