use itertools::Itertools;
use mule_rs::{CsvParser, Result, Value};

#[tokio::test]
pub async fn test_parsing_sales_10_weird() -> Result<()> {
    let mut parser = CsvParser::open_path("datasets/sales-10-weird.csv", ",", "\"", "\\").await?;
    let dataset = {
        let mut d = vec![];
        while let Some(line) = parser.next_line().await? {
            d.push(line.collect_vec());
        }
        d
    };

    let expected_dataset = vec![
        vec![
            Value("Region".to_string()),
            Value("Country".to_string()),
            Value("Item Type".to_string()),
            Value("Sales Channel".to_string()),
            Value("".to_string()),
            Value("Order Date".to_string()),
            Value("Order ID".to_string()),
            Value("\"Ship\" Date".to_string()),
            Value("Units Sold".to_string()),
            Value("Unit Price".to_string()),
            Value("Unit Cost".to_string()),
            Value("Total Revenue".to_string()),
            Value("Total Cost".to_string()),
            Value("Total Profit".to_string()),
        ],
        vec![
            Value("Australia and Oceania".to_string()),
            Value("Tuvalu".to_string()),
            Value("Baby Food".to_string()),
            Value("Offline".to_string()),
            Value("H".to_string()),
            Value("5/28/2010".to_string()),
            Value("669165933".to_string()),
            Value("6/27/2010".to_string()),
            Value("9925".to_string()),
            Value("255.28".to_string()),
            Value("159.42".to_string()),
            Value("2533654.00".to_string()),
            Value("1582243.50".to_string()),
            Value("951410.50".to_string()),
        ],
        vec![
            Value("Central America and the Caribbean".to_string()),
            Value("Grenada".to_string()),
            Value("Cereal".to_string()),
            Value("Online".to_string()),
            Value("C".to_string()),
            Value("8/22/2012".to_string()),
            Value("963881480".to_string()),
            Value("9/15/2012".to_string()),
            Value("2804".to_string()),
            Value("205.70".to_string()),
            Value("117.11".to_string()),
            Value("576782.80".to_string()),
            Value("328376.44".to_string()),
            Value("248406.36".to_string()),
        ],
        vec![
            Value("Europe".to_string()),
            Value("Russia".to_string()),
            Value("Office Supplies".to_string()),
            Value("Offline".to_string()),
            Value("L".to_string()),
            Value("5/2/2014".to_string()),
            Value("341417157".to_string()),
            Value("5/8/2014".to_string()),
            Value("1779".to_string()),
            Value("651.21".to_string()),
            Value("524.96".to_string()),
            Value("1158502.59".to_string()),
            Value("933903.84".to_string()),
            Value("224598.75".to_string()),
        ],
        vec![
            Value("Sub-Saharan Africa".to_string()),
            Value("Sao Tome and Principe".to_string()),
            Value("Fruits".to_string()),
            Value("Online".to_string()),
            Value("C".to_string()),
            Value("6/20/2014".to_string()),
            Value("514321792".to_string()),
            Value("7/5/2014".to_string()),
            Value("8102".to_string()),
            Value("9.33".to_string()),
            Value("6.92".to_string()),
            Value("75591.66".to_string()),
            Value("56065.84".to_string()),
            Value("19525.82".to_string()),
        ],
        vec![
            Value("Sub-Saharan Africa".to_string()),
            Value("Rwanda".to_string()),
            Value("Office Supplies".to_string()),
            Value("Offline".to_string()),
            Value("L".to_string()),
            Value("2/1/2013".to_string()),
            Value("115456712".to_string()),
            Value("2/6/2013".to_string()),
            Value("5062".to_string()),
            Value("651.21".to_string()),
            Value("524.96".to_string()),
            Value("3296425.02".to_string()),
            Value("2657347.52".to_string()),
            Value("639077.50".to_string()),
        ],
        vec![
            Value("".to_string()),
            Value("Solomon Islands".to_string()),
            Value("Baby Food".to_string()),
            Value("Online".to_string()),
            Value("C".to_string()),
            Value("2-4-2015".to_string()),
            Value("547995746".to_string()),
            Value("2/21/2015".to_string()),
            Value("2974".to_string()),
            Value("255.28".to_string()),
            Value("159.42".to_string()),
            Value(".72".to_string()),
            Value("474115.08".to_string()),
            Value("285087.64".to_string()),
        ],
        vec![
            Value("Sub-Saharan Africa".to_string()),
            Value("Angola".to_string()),
            Value("Household".to_string()),
            Value("Offline".to_string()),
            Value("M".to_string()),
            Value("4/23/2011".to_string()),
            Value("135425221".to_string()),
            Value("4/27/2011".to_string()),
            Value("4187".to_string()),
            Value("668.27".to_string()),
            Value("502.54".to_string()),
            Value("2798046.49".to_string()),
            Value("2104134.98".to_string()),
            Value("693911.51".to_string()),
        ],
        vec![
            Value("Sub-Saharan Africa".to_string()),
            Value("Burkina Faso".to_string()),
            Value("Vegetables".to_string()),
            Value("Online".to_string()),
            Value("H".to_string()),
            Value("7/17/2012".to_string()),
            Value("871543967".to_string()),
            Value("7/27/2012".to_string()),
            Value("8082".to_string()),
            Value("154.06".to_string()),
            Value("90.93".to_string()),
            Value("1245112.92".to_string()),
            Value("734896.26".to_string()),
            Value("510216.66".to_string()),
        ],
        vec![
            Value("Sub-Saharan Africa".to_string()),
            Value("Republic of the Congo".to_string()),
            Value("Personal Care".to_string()),
            Value("Offline".to_string()),
            Value("M".to_string()),
            Value("7/14/2015".to_string()),
            Value("770463311".to_string()),
            Value("8/25/2015".to_string()),
            Value("6070".to_string()),
            Value("81.73".to_string()),
            Value("56.67".to_string()),
            Value("496101.10".to_string()),
            Value("343986.90".to_string()),
            Value("152114.20".to_string()),
        ],
    ];

    assert_eq!(dataset, expected_dataset);
    Ok(())
}
