use itertools::Itertools;
use mule::{CsvParser, RawValue, Result};

#[tokio::test]
pub async fn test_parsing_sales_10_weird() -> Result<()> {
    let mut parser = CsvParser::open_path("datasets/sales-10-weird.csv", ",", "\"", "\\").await?;
    let dataset = {
        let mut d = vec![];
        while let Some(line) = parser.next_line().await? {
            d.push(line.collect_vec());
        }
        d
    };

    let expected_dataset = vec![
        vec![
            RawValue("Region".to_string()),
            RawValue("Country".to_string()),
            RawValue("Item Type".to_string()),
            RawValue("Sales Channel".to_string()),
            RawValue("".to_string()),
            RawValue("Order Date".to_string()),
            RawValue("Order ID".to_string()),
            RawValue("\"Ship\" Date".to_string()),
            RawValue("Units Sold".to_string()),
            RawValue("Unit Price".to_string()),
            RawValue("Unit Cost".to_string()),
            RawValue("Total Revenue".to_string()),
            RawValue("Total Cost".to_string()),
            RawValue("Total Profit".to_string()),
        ],
        vec![
            RawValue("Australia and Oceania".to_string()),
            RawValue("Tuvalu".to_string()),
            RawValue("Baby Food".to_string()),
            RawValue("Offline".to_string()),
            RawValue("H".to_string()),
            RawValue("5/28/2010".to_string()),
            RawValue("669165933".to_string()),
            RawValue("6/27/2010".to_string()),
            RawValue("9925".to_string()),
            RawValue("255.28".to_string()),
            RawValue("159.42".to_string()),
            RawValue("2533654.00".to_string()),
            RawValue("1582243.50".to_string()),
            RawValue("951410.50".to_string()),
        ],
        vec![
            RawValue("Central America and the Caribbean".to_string()),
            RawValue("Grenada".to_string()),
            RawValue("Cereal".to_string()),
            RawValue("Online".to_string()),
            RawValue("C".to_string()),
            RawValue("8/22/2012".to_string()),
            RawValue("963881480".to_string()),
            RawValue("9/15/2012".to_string()),
            RawValue("2804".to_string()),
            RawValue("205.70".to_string()),
            RawValue("117.11".to_string()),
            RawValue("576782.80".to_string()),
            RawValue("328376.44".to_string()),
            RawValue("248406.36".to_string()),
        ],
        vec![
            RawValue("Europe".to_string()),
            RawValue("Russia".to_string()),
            RawValue("Office Supplies".to_string()),
            RawValue("Offline".to_string()),
            RawValue("L".to_string()),
            RawValue("5/2/2014".to_string()),
            RawValue("341417157".to_string()),
            RawValue("5/8/2014".to_string()),
            RawValue("1779".to_string()),
            RawValue("651.21".to_string()),
            RawValue("524.96".to_string()),
            RawValue("1158502.59".to_string()),
            RawValue("933903.84".to_string()),
            RawValue("224598.75".to_string()),
        ],
        vec![
            RawValue("Sub-Saharan Africa".to_string()),
            RawValue("Sao Tome and Principe".to_string()),
            RawValue("Fruits".to_string()),
            RawValue("Online".to_string()),
            RawValue("C".to_string()),
            RawValue("6/20/2014".to_string()),
            RawValue("514321792".to_string()),
            RawValue("7/5/2014".to_string()),
            RawValue("8102".to_string()),
            RawValue("9.33".to_string()),
            RawValue("6.92".to_string()),
            RawValue("75591.66".to_string()),
            RawValue("56065.84".to_string()),
            RawValue("19525.82".to_string()),
        ],
        vec![
            RawValue("Sub-Saharan Africa".to_string()),
            RawValue("Rwanda".to_string()),
            RawValue("Office Supplies".to_string()),
            RawValue("Offline".to_string()),
            RawValue("L".to_string()),
            RawValue("2/1/2013".to_string()),
            RawValue("115456712".to_string()),
            RawValue("2/6/2013".to_string()),
            RawValue("5062".to_string()),
            RawValue("651.21".to_string()),
            RawValue("524.96".to_string()),
            RawValue("3296425.02".to_string()),
            RawValue("2657347.52".to_string()),
            RawValue("639077.50".to_string()),
        ],
        vec![
            RawValue("".to_string()),
            RawValue("Solomon Islands".to_string()),
            RawValue("Baby Food".to_string()),
            RawValue("Online".to_string()),
            RawValue("C".to_string()),
            RawValue("2-4-2015".to_string()),
            RawValue("547995746".to_string()),
            RawValue("2/21/2015".to_string()),
            RawValue("2974".to_string()),
            RawValue("255.28".to_string()),
            RawValue("159.42".to_string()),
            RawValue(".72".to_string()),
            RawValue("474115.08".to_string()),
            RawValue("285087.64".to_string()),
        ],
        vec![
            RawValue("Sub-Saharan Africa".to_string()),
            RawValue("Angola".to_string()),
            RawValue("Household".to_string()),
            RawValue("Offline".to_string()),
            RawValue("M".to_string()),
            RawValue("4/23/2011".to_string()),
            RawValue("135425221".to_string()),
            RawValue("4/27/2011".to_string()),
            RawValue("4187".to_string()),
            RawValue("668.27".to_string()),
            RawValue("502.54".to_string()),
            RawValue("2798046.49".to_string()),
            RawValue("2104134.98".to_string()),
            RawValue("693911.51".to_string()),
        ],
        vec![
            RawValue("Sub-Saharan Africa".to_string()),
            RawValue("Burkina Faso".to_string()),
            RawValue("Vegetables".to_string()),
            RawValue("Online".to_string()),
            RawValue("H".to_string()),
            RawValue("7/17/2012".to_string()),
            RawValue("871543967".to_string()),
            RawValue("7/27/2012".to_string()),
            RawValue("8082".to_string()),
            RawValue("154.06".to_string()),
            RawValue("90.93".to_string()),
            RawValue("1245112.92".to_string()),
            RawValue("734896.26".to_string()),
            RawValue("510216.66".to_string()),
        ],
        vec![
            RawValue("Sub-Saharan Africa".to_string()),
            RawValue("Republic of the Congo".to_string()),
            RawValue("Personal Care".to_string()),
            RawValue("Offline".to_string()),
            RawValue("M".to_string()),
            RawValue("7/14/2015".to_string()),
            RawValue("770463311".to_string()),
            RawValue("8/25/2015".to_string()),
            RawValue("6070".to_string()),
            RawValue("81.73".to_string()),
            RawValue("56.67".to_string()),
            RawValue("496101.10".to_string()),
            RawValue("343986.90".to_string()),
            RawValue("152114.20".to_string()),
        ],
    ];

    assert_eq!(dataset, expected_dataset);
    Ok(())
}
